Repository michelin/kstreamplify, pull requests merged in 2023-07, with the labels that each got.

#56 🛠 Reorder DLQ loading for topic with serde
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsInitializer.java
Labels: bug

#54 Implement deduplication utils
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DedupKeyProcessor.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DedupKeyValueProcessor.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DedupWithPredicateProcessor.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DeduplicationUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/ProcessingResult.java
Labels: enhancement, feature

#57 🧹 Javadoc error cleanup
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DedupKeyProcessor.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DedupKeyValueProcessor.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DedupWithPredicateProcessor.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DeduplicationUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/ProcessingResult.java
Labels: documentation

#60 Fix Spring Boot properties initialisation
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/initializer/SpringKafkaStreamsInitializer.java
Labels: bug

#59 Improve Javadoc
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/constants/DefaultProbeHttpServerConstants.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/constants/HttpServerConstants.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/constants/InitializerConstants.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/constants/PropertyConstants.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/converter/JsonToAvroConverter.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsInitializer.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/model/RestServiceResponse.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/properties/PropertiesUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/rest/DefaultProbeController.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/services/ProbeService.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicWithSerde.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/rest/SpringProbeController.java
Labels: documentation

#66 Add SonarCloud analysis
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_main.yml
  pom.xml
Labels: feature
