Repository michelin/kstreamplify, pull requests merged in 2023-11, with the labels that each got.

#123 Fix Dlq production exception handler unit tests
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/error/DlqProductionExceptionHandlerTest.java
Labels: bug

#126 Update tests gif with new implementation
  .readme/gif/test.gif
Labels: documentation

#133 Update ProbeService.java ready only if running
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/services/ProbeService.java
Labels: bug

#135 Prevent Sonar analysis from running and failing on forks
  .github/workflows/on_pull_request.yml
Labels: enhancement
