Repository michelin/kstreamplify, pull requests merged in 2023-06, with the labels that each got.

#40 Property loading fixes and code cleanup
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/constants/DefaultProbeHttpServerConstants.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/constants/InitializerConstants.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/constants/PropertyConstants.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/constants/TopicConstants.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/initializer/KafkaStreamsInitializer.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/properties/PropertiesUtils.java
  kstreamplify-spring-boot/src/main/java/io/github/michelin/kstreamplify/initializer/SpringKafkaStreamsInitializer.java
  kstreamplify-spring-boot/src/main/java/io/github/michelin/kstreamplify/rest/SpringProbeController.java
  kstreamplify-spring-boot/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: bug

#43 Fixed kafka properties loading in case of SpringBoot implementation
  kstreamplify-spring-boot/src/main/java/io/github/michelin/kstreamplify/initializer/SpringKafkaStreamsInitializer.java
Labels: bug

#44 Removed unnecessary static keyword
  kstreamplify-core-test/src/main/java/io/github/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core-test/src/test/java/io/github/michelin/kstreamplify/TopologyErrorHandlerTest.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/error/ProcessingError.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/error/TopologyErrorHandler.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/initializer/KafkaStreamsInitializer.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/services/ConvertTopology.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/services/ProbeService.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/utils/SerdesUtils.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/utils/TopicUtils.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/utils/TopicWithSerde.java
  kstreamplify-spring-boot/src/main/java/io/github/michelin/kstreamplify/properties/KafkaProperties.java
  kstreamplify-spring-boot/src/main/java/io/github/michelin/kstreamplify/rest/SpringProbeController.java
Labels: beginner

#41 Remove unecessary Avro module
  README.md
  kstreamplify-avro/avro-error/pom.xml
  kstreamplify-avro/avro-testing/pom.xml
  kstreamplify-avro/pom.xml
  kstreamplify-core/pom.xml
  kstreamplify-core/src/main/avro/kafka-error.avsc
  kstreamplify-core/src/test/avro/kafka-test.avsc
  kstreamplify-spring-boot/pom.xml
  pom.xml
Labels: enhancement

#46 Rename main artifact to Kstreamplify
  kstreamplify-core-test/pom.xml
  kstreamplify-core/pom.xml
  kstreamplify-spring-boot/pom.xml
  pom.xml
Labels: enhancement

#47 Topic with Serde implementation
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/constants/PropertyConstants.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/constants/TopicConstants.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/context/KafkaStreamsExecutionContext.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/properties/PropertiesUtils.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/services/ProbeService.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/utils/SerdesUtils.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/utils/TopicUtils.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/utils/TopicWithSerde.java
  kstreamplify-core/src/main/java/io/github/michelin/kstreamplify/utils/WindowStateStoreUtils.java
Labels: feature
