Repository michelin/kstreamplify, pull requests merged in 2023-09, with the labels that each got.

#82 Fix missing handling of generic record containing Instants in GSON converter
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/converter/AvroToJsonConverter.java
Labels: bug

#85 Add on start documentation
  README.md
Labels: documentation

#75 Change way of working on DlqDeserializationExceptionHandler.
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqDeserializationExceptionHandler.java
Labels: enhancement

#68 Improve javadoc (#36)
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/context/KafkaStreamsExecutionContext.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/rest/DefaultProbeController.java
Labels: documentation

#91 Add documentation for interactive queries
  README.md
Labels: documentation

#62 Add unit tests coverage
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/TopologyErrorHandlerTest.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/converter/JsonToAvroConverter.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqDeserializationExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqProductionExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/ProcessingResult.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicWithSerde.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/WindowStateStoreUtils.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/converter/JsonToAvroConverterTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/deduplication/DedupKeyProcessorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/deduplication/DedupKeyValueProcessorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/deduplication/DedupWithPredicateProcessorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/initializer/KafkaStreamsInitializerTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/initializer/KafkaStreamsStarterTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/properties/RocksDbConfigTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/rest/DlqDeserializationExceptionHandlerTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/rest/DlqExceptionHandlerTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/rest/DlqProductionExceptionHandlerTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/rest/GenericErrorProcessorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/rest/ProcessingErrorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/rest/ProcessingResultTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/services/ProbeServiceTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/utils/TopicWithSerdesUnitTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/utils/WindowStateStoreUtilsTest.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/initializer/SpringKafkaStreamsInitializerTest.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/rest/SpringProbeControllerTest.java
  lombok.config
  pom.xml
Labels: enhancement

#93 Improve README with gif animations
  .readme/gif/dlq.gif
  .readme/gif/full-topology.gif
  .readme/gif/on-start.gif
  .readme/gif/serdes.gif
  .readme/gif/test.gif
  .readme/gif/topology-bean.gif
  .readme/gif/topology.gif
  README.md
Labels: documentation

#103 Add passphrase for tagging
  .github/workflows/tag.yml
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/error/DlqDeserializationExceptionHandlerTest.java
Labels: enhancement

#104 Fix pom update in tag job
  .github/workflows/tag.yml
Labels: bug

#105 Add Javadoc in README
  README.md
Labels: documentation

#106 Update README with test count and sonatype badges
  README.md
Labels: documentation
