Repository michelin/kstreamplify, pull requests merged in 2024-04, with the labels that each got.

#178 Add the possibility to customize the uncaught exception handler
  README.md
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsInitializer.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsStarter.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/initializer/KafkaStreamsStarterTest.java
Labels: feature

#191 Fix typo in exception handler documentation
  README.md
Labels: documentation

#187 Add logical types for JSON to Avro converters
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/converter/AvroToJsonConverter.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/converter/JsonToAvroConverter.java
  kstreamplify-core/src/test/avro/kafka-test.avsc
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/converter/AvroToJsonConverterTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/converter/JsonToAvroConverterTest.java
Labels: bug
