Repository michelin/kstreamplify, pull requests merged in 2024-10, with the labels that each got.

#244 Give the possibility to override the properties in KafkaStreamsStarterTest
  kstreamplify-core-test/src/main/java/com/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/OverridePropertiesTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/TopologyErrorHandlerTest.java
Labels: feature

#243 Add interactive queries for Window stores
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/server/KafkaStreamsHttpServer.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/service/InteractiveQueriesService.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/service/interactivequeries/InteractiveQueriesService.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/service/interactivequeries/KeyValueStoreService.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/service/interactivequeries/WindowStoreService.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/integration/InteractiveQueriesIntegrationTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/service/interactivequeries/KeyValueStoreServiceTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/service/interactivequeries/WindowStoreServiceTest.java
  kstreamplify-spring-boot/pom.xml
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/config/BeanConfig.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/controller/InteractiveQueriesController.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/controller/InteractiveQueriesControllerTest.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/integration/InteractiveQueriesIntegrationTest.java
Labels: feature

#250 Update interactive queries documentation with window store
  README.md
Labels: documentation

#251 Add documentation about overriding properties in unit tests
  README.md
  kstreamplify-core-test/src/main/java/com/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/OverridePropertiesTest.java
Labels: documentation

#256 Remove forRemoval warnings on deprecation
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/SerdesUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicWithSerde.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/WindowStateStoreUtils.java
Labels: enhancement

#257 Restore create topic methods for unit tests
  kstreamplify-core-test/src/main/java/com/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/TopologyErrorHandlerTest.java
Labels: bug

#260 Remove deprecated usage of KafkaContainer
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/integration/container/KafkaIntegrationTest.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/integration/container/KafkaIntegrationTest.java
Labels: bug

#265 Bump com.puppycrawl.tools:checkstyle from 10.18.2 to 10.19.0
  kstreamplify-core-test/src/main/java/com/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/context/KafkaStreamsExecutionContext.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DeduplicationUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/ProcessingResult.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsStarter.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/serde/TopicWithSerde.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/topic/TopicUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicWithSerde.java
  pom.xml
Labels: dependencies
