Repository michelin/kstreamplify, pull requests merged in 2024-11, with the labels that each got.

#270 Fix references to SerdesUtils
  README.md
Labels: documentation

#272 Add applicationId in KafkaError schema
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/TopologyErrorHandlerTest.java
  kstreamplify-core/src/main/avro/kafka-error.avsc
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqDeserializationExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqProductionExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/GenericErrorProcessor.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/error/ProcessingErrorTest.java
Labels: enhancement

#277 Do not expose full configuration in the logs to avoid to leak secrets.
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/context/KafkaStreamsExecutionContext.java
Labels: enhancement

#278 Bump Kafka Stream to v3.6.2 to avoid KAFKA-16017 issue
  pom.xml
Labels: dependencies

#274 Give properties when building the topology
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsInitializer.java
Labels: enhancement

#279 Bump Kafka Stream to v3.6.2 to avoid KAFKA-16017 issue
  pom.xml
Labels: dependencies

#280 Do not expose full configuration in the logs to avoid to leak secrets
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/context/KafkaStreamsExecutionContext.java
Labels: enhancement

#282 Restore RocksDb config and mark as deprecated
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/properties/RocksDbConfig.java
Labels: bug
