Repository michelin/kstreamplify, pull requests merged in 2025-02, with the labels that each got.

#309 Fix typo in SerdesUtils documentation
  README.md
Labels: documentation

#310 Remove deprecated TopicUtils
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicUtils.java
Labels: enhancement

#311 Expose Kafka and Spring Boot versions in use
  README.md
Labels: documentation

#316 Add Maven cache
  .github/workflows/pull_request.yml
  .github/workflows/push_main.yml
  .github/workflows/release.yml
  pom.xml
Labels: ci/cd

#318 Enhance processing result tests and Java documentation
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqDeserializationExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqProductionExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/ProcessingResult.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/error/ProcessingResultTest.java
Labels: test

#320 Prevent SonarQube running on fork
  .github/workflows/pull_request.yml
  .github/workflows/push_main.yml
Labels: ci/cd

#321 Update variable used to skip Sonar job on fork
  .github/workflows/pull_request.yml
Labels: ci/cd

#323 Fix Schema Registry URL not being defined in default testing properties
  kstreamplify-core-test/src/main/java/com/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/OverridePropertiesTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/TopologyErrorHandlerTest.java
Labels: bug
