Repository michelin/kstreamplify, pull requests merged in 2025-04, with the labels that each got.

#348 Ensure topic prefixes are applied in tests with TopicWithSerde API
  kstreamplify-core-test/src/main/java/com/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/GetSpecificPropertiesTest.java
Labels: bug

#350 Fix Spotless multi-modules build
  pom.xml
Labels: ci/cd

#351 Update to Maven wrapper 3.2.2
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: ci/cd

#352 Add documentation for Java app and Processor API error handling
  README.md
Labels: documentation

#353 Add documentation for TopicWithSerde API and unit testing
  README.md
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/GetSpecificPropertiesTest.java
  kstreamplify-core-test/src/test/java/com/michelin/kstreamplify/TopologyErrorHandlerTest.java
  kstreamplify-core/src/test/avro/kafka-user.avsc
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/converter/AvroToJsonConverterTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/deduplication/DedupKeyProcessorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/deduplication/DedupKeyValueProcessorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/deduplication/DedupWithPredicateProcessorTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/keyvalue/KeyValueIntegrationTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/keyvalue/TimestampedKeyValueIntegrationTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/window/TimestampedWindowIntegrationTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/window/WindowIntegrationTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/service/interactivequeries/keyvalue/KeyValueServiceTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/service/interactivequeries/keyvalue/TimestampedKeyValueServiceTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/service/interactivequeries/window/TimestampedWindowStoreServiceTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/service/interactivequeries/window/WindowStoreServiceTest.java
  kstreamplify-spring-boot/src/test/avro/kafka-person.avsc
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/keyvalue/KeyValueIntegrationTest.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/keyvalue/TimestampedKeyValueIntegrationTest.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/window/TimestampedWindowIntegrationTest.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/integration/interactivequeries/window/WindowIntegrationTest.java
Labels: documentation

#354 Fix warns in Javadoc and build
  README.md
  kstreamplify-core-test/src/main/java/com/michelin/kstreamplify/KafkaStreamsStarterTest.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/context/KafkaStreamsExecutionContext.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/converter/AvroToJsonConverter.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/converter/JsonToAvroConverter.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/deduplication/DeduplicationUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqDeserializationExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/DlqProductionExceptionHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/error/TopologyErrorHandler.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsInitializer.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/initializer/KafkaStreamsStarter.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/properties/RocksDbConfig.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/property/PropertiesUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/serde/SerdesUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/serde/TopicWithSerde.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/service/KubernetesService.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/service/TopologyService.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/store/RocksDbConfig.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/store/StateStoreRecord.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/store/StreamsMetadata.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/store/WindowStateStoreUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/topic/TopicUtils.java
  kstreamplify-core/src/main/java/com/michelin/kstreamplify/utils/TopicWithSerde.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/error/DlqDeserializationExceptionHandlerTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/error/DlqProductionExceptionHandlerTest.java
  kstreamplify-core/src/test/java/com/michelin/kstreamplify/integration/container/KafkaIntegrationTest.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/config/BeanConfig.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/controller/ControllerExceptionHandler.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/controller/InteractiveQueriesController.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/controller/KubernetesController.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/controller/TopologyController.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/initializer/SpringBootKafkaStreamsInitializer.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/opentelemetry/OpenTelemetryConfig.java
  kstreamplify-spring-boot/src/main/java/com/michelin/kstreamplify/property/KafkaProperties.java
  kstreamplify-spring-boot/src/test/java/com/michelin/kstreamplify/opentelemetry/OpenTelemetryConfigTest.java
  pom.xml
Labels: documentation

#363 Add documentation about OpenTelemetry Agent v2
  README.md
Labels: documentation
